package edu.aau.se2.model;

public abstract class TerritoryID {
    public static int Argentina = 1;
    public static int Brazil = 2;
    public static int Peru = 3;
    public static int Venezuela = 4;
    public static int Alaska = 5;
    public static int WesternCanada = 6;
    public static int CentralAmerica = 7;
    public static int EasternUS = 8;
    public static int Greenland = 9;
    public static int NorthwestTerritory = 10;
    public static int CentralCanada = 11;
    public static int EasternCanada = 12;
    public static int WesternUS = 13;
    public static int CentralAfrica = 14;
    public static int EastAfrica = 15;
    public static int Egypt = 16;
    public static int Madagascar = 17;
    public static int NorthAfrica = 18;
    public static int SouthAfrica = 19;
    public static int GreatBritain = 20;
    public static int Iceland = 21;
    public static int NorthernEurope = 22;
    public static int Scandinavia = 23;
    public static int SouthernEurope = 24;
    public static int Ukraine = 25;
    public static int WesternEurope = 26;
    public static int EasternAustralia = 27;
    public static int Indonesia = 28;
    public static int NewGuinea = 29;
    public static int WesternAustralia = 30;
    public static int Afghanistan = 31;
    public static int China = 32;
    public static int India = 33;
    public static int Irkutsk = 34;
    public static int Japan = 35;
    public static int Kamchatka = 36;
    public static int MiddleEast = 37;
    public static int Mongolia = 38;
    public static int SoutheastAsia = 39;
    public static int Siberia = 40;
    public static int Ural = 41;
    public static int Yakutsk = 42;
}
